module Potassium
  VERSION = "6.1.0"
  RUBY_VERSION = "2.7.0"
  RAILS_VERSION = "~> 6.0.2"
  RUBOCOP_VERSION = "~> 0.82.0"
  POSTGRES_VERSION = "11.3"
  MYSQL_VERSION = "5.7"
  NODE_VERSION = "12"
end
