module Potassium
  VERSION = "6.2.0"
  RUBY_VERSION = "2.7.0"
  RAILS_VERSION = "~> 6.0.2"
  RUBOCOP_VERSION = "~> 1.9"
  RUBOCOP_RSPEC_VERSION = "~> 2.2"
  POSTGRES_VERSION = "11.3"
  MYSQL_VERSION = "5.7"
  NODE_VERSION = "12"
end
